const dotaAccounts = [
    {
        title: "Срочно продам",
        Decency: 9000,
        description: "Много аркан и есть редкие сеты на тиника. Отдаю вместе с родной почтой или можем привязать на вашу.",
        MMR: 1500,
        price: 53,
        Guarantee: "3 дня",
        steamLevel: 30,
        NOfMatches: 534,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Продам с высоким рейтингом",
        Decency: 9500,
        description: "Этот аккаунт имеет высокий MMR и большой выбор сетов для различных героев. Готов к продаже со всеми гарантиями.",
        MMR: 5000,
        price: 120,
        Guarantee: "7 дней",
        steamLevel: 40,
        NOfMatches: 423,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Новичок в Доте",
        Decency: 7500,
        description: "Аккаунт для тех, кто только начинает свой путь в мире Доты. Низкий MMR, но много потенциала для роста.",
        MMR: 800,
        price: 20,
        Guarantee: "2 дня",
        steamLevel: 15,
        NOfMatches: 167,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Коллекционер аркан",
        Decency: 9200,
        description: "Аккаунт с большой коллекцией аркан и уникальных предметов. Подходит для тех, кто ценит внешний вид героев.",
        MMR: 2500,
        price: 80,
        Guarantee: "5 дней",
        steamLevel: 35,
        NOfMatches: 352,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Любитель поддержки",
        Decency: 8700,
        description: "Аккаунт с высоким MMR в роли поддержки. Имеет большой опыт в саппорт-игре и множество подходящих сетов.",
        MMR: 4200,
        price: 90,
        Guarantee: "6 дней",
        steamLevel: 25,
        NOfMatches: 897,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Легенда керри",
        Decency: 9600,
        description: "Этот аккаунт прославился благодаря великолепной игре на керри. Высокий MMR и коллекция редких керри-сетов.",
        MMR: 5220,
        price: 150,
        Guarantee: "10 дней",
        steamLevel: 50,
        NOfMatches: 1260,
        in_favorites: false, 
        in_cart: false,
    },
    {
        title: "Герой среди друзей",
        Decency: 8800,
        description: "Этот аккаунт идеально подходит для игр в команде с друзьями. Много сетов для героев, обеспечивающих веселье в игре.",
        MMR: 3500,
        price: 60,
        Guarantee: "4 дня",
        steamLevel: 32,
        NOfMatches: 345,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Профессиональный игрок",
        Decency: 10500,
        description: "Этот аккаунт принадлежит профессиональному игроку с выдающимися навыками. Высокий MMR и уникальные достижения.",
        MMR: 5600,
        price: 200,
        Guarantee: "15 дней",
        steamLevel: 55,
        NOfMatches: 1357,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Аккаунт для хорошего начала",
        Decency: 8000,
        description: "Новый аккаунт для людей которые только начинают знакомиться с дотой.",
        MMR: 100,
        price: 10,
        Guarantee: "10 дней",
        steamLevel: 20,
        NOfMatches: 61,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Мастер игры",
        Decency: 10000,
        description: "Аккаунт с великолепными навыками. Высокий MMR.",
        MMR: 6000,
        price: 200,
        Guarantee: "12 дней",
        steamLevel: 45,
        NOfMatches: 1563,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Коллекционер курьеров",
        Decency: 8800,
        description: "Этот аккаунт известен своей уникальной коллекцией курьеров. Подходит для любителей разнообразных скинов.",
        MMR: 3200,
        price: 70,
        Guarantee: "5 дней",
        steamLevel: 36,
        NOfMatches: 352,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Тимбилдер",
        Decency: 9100,
        description: "Аккаунт с уникальным тимбилдом. Высокий MMR и множество командных сетов для тех, кто любит играть в команде.",
        MMR: 4800,
        price: 100,
        Guarantee: "9 дней",
        steamLevel: 38,
        NOfMatches: 731,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Исследователь новых стратегий",
        Decency: 8300,
        description: "Этот аккаунт известен своими нестандартными стратегиями. Подходит для тех, кто ищет новые подходы в игре.",
        MMR: 3000,
        price: 50,
        Guarantee: "4 дня",
        steamLevel: 20,
        NOfMatches: 354,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Аккаунт с открытым рейтингом",
        Decency: 11000,
        description: "Аккаунт для тех кого забанили, но он хочет играть в рейтинг",
        MMR: 0,
        price: 5,
        Guarantee: "10 дней",
        steamLevel: 5,
        NOfMatches: 578,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Много Аркан-сетов",
        Decency: 6574,
        description: "Аккаунт для коллекционеров, имеются почти все аркан-сеты",
        MMR: 3400,
        price: 650,
        Guarantee: "7 дней",
        steamLevel: 40,
        NOfMatches: 420,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Аккаунт с минимальным MMR",
        Decency: 8130,
        description: "Самый низкий MMR на рынке. Идеальный выбор для тех, кто хочет испытать вызов.",
        MMR: 0,
        price: 5,
        Guarantee: "3 дня",
        steamLevel: 5,
        NOfMatches: 5,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Старый мейн-аккаунт",
        Decency: 8432,
        description: "Раньше очень часто играл, высокий MMR и много разных сетов.",
        MMR: 5154,
        price: 160,
        Guarantee: "5 дней",
        steamLevel: 60,
        NOfMatches: 986,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Новичок с низким MMR",
        Decency: 7212,
        description: "Аккаунт для начинающих игроков. Низкий MMR, но большое желание учиться.",
        MMR: 200,
        price: 15,
        Guarantee: "1 день",
        steamLevel: 10,
        NOfMatches: 20,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Продвинутый герой",
        Decency: 9800,
        description: "Аккаунт с высоким MMR и множеством достижений. Идеальный выбор для опытных игроков.",
        MMR: 3800,
        price: 110,
        Guarantee: "8 дней",
        steamLevel: 42,
        NOfMatches: 789,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Герой леса",
        Decency: 8500,
        description: "Любителям игры в лесу - аккаунт с множеством сетов для лесных героев.",
        MMR: 3000,
        price: 75,
        Guarantee: "5 дней",
        steamLevel: 30,
        NOfMatches: 502,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Искусство контроля",
        Decency: 9100,
        description: "Аккаунт с высоким MMR и отличными навыками контроля карты. Идеален для игры на поддержке.",
        MMR: 4100,
        price: 100,
        Guarantee: "8 дней",
        steamLevel: 38,
        NOfMatches: 786,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Мастерский керри",
        Decency: 9700,
        description: "Этот аккаунт специализируется на игре на керри. Отличный выбор для тех, кто хочет вести свою команду к победе.",
        MMR: 4500,
        price: 140,
        Guarantee: "10 дней",
        steamLevel: 48,
        NOfMatches: 1123,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Мастер стример",
        Decency: 9300,
        description: "Аккаунт принадлежит популярному стримеру, высокий MMR и эксклюзивные предметы. Покупка = поддержка контента!",
        MMR: 4800,
        price: 180,
        Guarantee: "10 дней",
        steamLevel: 50,
        NOfMatches: 1045,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Тренер новичков",
        Decency: 8500,
        description: "Аккаунт среднего MMR, но с большим опытом. Идеально подходит для того, чтобы обучать новых игроков.",
        MMR: 1680,
        price: 40,
        Guarantee: "5 дней",
        steamLevel: 25,
        NOfMatches: 405,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Аккаунт с легендарным прошлым",
        Decency: 8600,
        description: "Этот аккаунт принадлежал легендарному игроку в прошлом. Высокий MMR и история побед в знаменитых матчах.",
        MMR: 4000,
        price: 120,
        Guarantee: "8 дней",
        steamLevel: 40,
        NOfMatches: 789,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Стартовый путь в Доте",
        Decency: 6600,
        description: "Аккаунт для тех, кто только начинает свой путь в мире Доты. Низкий MMR, но большой потенциал для роста.",
        MMR: 800,
        price: 20,
        Guarantee: "4 дня",
        steamLevel: 15,
        NOfMatches: 104,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Начинающий герой",
        Decency: 6200,
        description: "Аккаунт для тех, кто только начал играть в Доту. Низкий MMR, но много желания познать все тонкости игры.",
        MMR: 950,
        price: 25,
        Guarantee: "5 дней",
        steamLevel: 12,
        NOfMatches: 134,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Средний уровень мастерства",
        Decency: 2400,
        description: "Аккаунт с средним MMR, подходит для игроков, желающих улучшить свои навыки в игре.",
        MMR: 2450,
        price: 45,
        Guarantee: "5 дней",
        steamLevel: 22,
        NOfMatches: 268,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Поддержка в действии",
        Decency: 2250,
        description: "Аккаунт с фокусом на роли поддержки. Средний MMR и много опыта в поддержке своей команды.",
        MMR: 2200,
        price: 35,
        Guarantee: "4 дня",
        steamLevel: 20,
        NOfMatches: 189,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Мастер мидлейн",
        Decency: 10500,
        description: "Аккаунт с высоким MMR и множеством сетов для мидлейн героев. Готов к продаже со всеми гарантиями.",
        MMR: 5600,
        price: 180,
        Guarantee: "10 дней",
        steamLevel: 45,
        NOfMatches: 1000,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Мастер оффлейна",
        Decency: 10800,
        description: "Аккаунт с высоким MMR и множеством сетов для оффлейн героев. Готов к продаже со всеми гарантиями.",
        MMR: 5400,
        price: 175,
        Guarantee: "12 дней",
        steamLevel: 48,
        NOfMatches: 1100,
        in_favorites: false,
        in_cart: false,
    },
    {
        title: "Эксперт в рошане",
        Decency: 11000,
        description: "Этот аккаунт принадлежит игроку, который мастерски контролирует Рошана. Высокий MMR и уникальные достижения.",
        MMR: 5500,
        price: 195,
        Guarantee: "14 дней",
        steamLevel: 52,
        NOfMatches: 1250,
        in_favorites: false,
        in_cart: false,
    }
];
